### ISSUE TITLE
Publishing from within Travis CI

### ISSUE THREAD

**Issue by ghpabs** [shinnn/gulp-gh-pages#80]
Would it be possible to use this plugin from within Travis CI?

Let's say that in the `.travis.yml` I trigger `gulp publish` in the `after_success`. How would that work?

**Comment by shinnn** [comment]
Yes, it's possible.

> How would that work?

You can use https://stackoverflow.com/ for support question.

**Comment by Snugug** [comment]
For anyone looking to do this in the future, here's how I was able to get it to work:

```yaml
before_deploy: git config --global user.email publish@travis.github && git config --global user.name "Travis"
deploy:
  - edge: true
    skip_cleanup: true
    provider: script
    script: gulp publish
    on:
      branch: master
```

Before deploys, I set the Travis email and name, and then use a script deploy provider to run my `gulp publish` command which runs this script. Deploys great!
